export const palavrasart = [
  "o que é arte arte é a expressão humana. pode ser ideia, processo ou pergunta. reflete valores, crenças e estruturas sociais de cada época e cultura.",
  "funções da arte serve para estética, crítica, política, religião, comunicação e terapia. exemplo: grafite que denuncia problemas sociais.",
  "elementos visuais da arte ponto, linha, forma, cor, textura, espaço, luz e sombra. são usados para compor, expressar e dar sentido visual à obra.",
  "elementos musicais da arte melodia linha principal, harmonia acordes, ritmo tempo, timbre qualidade sonora, dinâmica volume. formam a estrutura e emoção da música.",
  "elementos cênicos da arte corpo movimento, voz fala, espaço palco, tempo ritmo, personagem criação. dão vida à cena no teatro e na dança.",
  "pré-história e arte rupestre pinturas em cavernas feitas com pigmentos naturais. funções ritualísticas, registros diários ou espirituais. exemplo: lascaux, altamira.",
  "arte egípcia monumental e simbólica. pirâmides, templos, obeliscos, hieróglifos. seguia a lei da frontalidade e um cânone rígido.",
  "arte grega antiga buscava perfeição e proporção. esculturas atléticas, ordens arquitetônicas dórica, jônica, coríntia. teatro com tragédias e comédias.",
  "arte romana antiga prática e realista. usou arcos e abóbadas coliseu, aquedutos, esculturas realistas bustos, mosaicos como narrativa decorativa.",
  "arte medieval românico religiosa e didática. igrejas com paredes grossas, arcos redondos, esculturas que ensinavam a bíblia. mosteiros eram centros culturais.",
  "arte medieval gótica verticalidade e luz. arcos ogivais, vitrais coloridos, abóbadas cruzadas. esculturas mais expressivas, objetivo de tocar o divino.",
  "renascimento cultural retomou a antiguidade com foco no homem e ciência. leonardo, michelangelo e rafael inovaram na arte com técnica e humanidade.",
  "maneirismo transição tensa. figuras alongadas, cores estranhas, composições complexas. rompeu com o equilíbrio do renascimento. artistas el greco, parmigianino.",
  "barroco drama e contraste. claro-escuro, emoção forte. artistas caravaggio, rembrandt, aleijadinho. surgiu na resposta à reforma e contrarreforma.",
  "rococó leveza e luxo. cores suaves, cenas aristocráticas e decoração rebuscada. celebra o prazer e a elite, saindo do foco religioso do barroco.",
  "neoclassicismo retorno à razão e forma clássica. influenciado pela revolução francesa e iluminismo. jacques-louis david destacou-se com temas heroicos.",
  "romantismo emoção acima da razão. exaltou natureza, morte, nacionalismo e sentimentos profundos. caspar david friedrich pintou paisagens introspectivas.",
  "realismo foco na realidade objetiva. mostrava o cotidiano das classes baixas com crítica social. courbet dizia que a arte é a representação do real.",
  "naturalismo realismo radical. mostrava o ser humano como resultado do meio, genética e sociedade. zola e courbet como principais nomes.",
  "impressionismo captura da luz no momento. pinceladas soltas, sem contornos rígidos. monet e renoir pintaram cenas urbanas e da natureza ao ar livre.",
  "pós-impressionismo artistas seguiram caminhos únicos. van gogh usou emoção e cor vibrante. cézanne buscou estrutura. gauguin explorou simbolismo e culturas exóticas.",
  "expressionismo foco na emoção distorcida. arte subjetiva, com cores fortes e traços agressivos. denunciava angústias sociais e existenciais.",
  "cubismo picasso e braque fragmentaram a realidade em formas geométricas. perspectiva múltipla e quebra da ilusão do espaço tridimensional.",
  "dadaísmo antiarte e provocação. surgiu como protesto ao absurdo da guerra. usava colagens, objetos prontos e humor sarcástico.",
  "surrealismo baseado nos sonhos e no inconsciente. dalí e magritte criaram cenas irreais com lógica absurda e visual detalhado.",
  "arte moderna experimentação e ruptura com o passado. matisse, mondrian e kandinsky buscaram novas formas, cores e significados.",
  "arte contemporânea pluralidade total. instalações, performances, arte digital. questiona o que é arte. reage ao mundo globalizado e à tecnologia.",
  "arte abstrata não representa objetos reconhecíveis, focando em formas, cores e linhas. kandinsky é pioneiro. liberdade total de expressão.",
  "arte pop cultura popular e consumo. andy warhol usou imagens de quadrinhos e produtos. crítica e celebração da sociedade de massa.",
  "minimalismo formas simples e cores neutras. busca a essência, eliminando o excesso. donald judd e sol lewitt exploraram a simplicidade e repetição.",
  "arte conceitual a ideia é mais importante que a obra. a arte pode ser texto, instrução, não precisa ser um objeto físico. joseph kosuth e yoko ono.",
  "graffiti arte de rua e protesto. murais e pichações em espaços públicos. banksy é um dos mais famosos, com críticas sociais e políticas.",
  "arte cinética obras com movimento real ou ilusório. calder criou móbiles que se movem com o ar. busca interação e dinamismo.",
  "land art intervenções na paisagem natural. usa elementos como terra, pedras, água. robert smithson fez o 'spiral jetty'. questiona a relação arte-natureza.",
  "performance arte que envolve a ação do artista. pode ser um evento, um ritual, uma interação com o público. marina abramović é um ícone.",
  "instalação arte que ocupa um espaço, transformando o ambiente. o público faz parte da obra, interagindo com ela. pode usar luz, som, objetos.",
  "videoarte arte feita com vídeo. pode ser crítica, experimental ou narrativa. nam june paik é considerado o pai da videoarte.",
  "fotografia arte de capturar imagens com luz. da vinci e daguerre foram pioneiros. evoluiu de técnica para forma de expressão artística."
];