export const palavrashis = [
  "brasil colônia a colonização portuguesa no brasil começou com o extrativismo do pau-brasil e evoluiu para o sistema de capitanias hereditárias e o ciclo do açúcar, usando mão de obra escravizada.",
  "inconfidência mineira movimento separatista ocorrido no século xviii em minas gerais, inspirado pelas ideias iluministas e contra os altos impostos da coroa portuguesa.",
  "era vargas período em que getúlio vargas governou o brasil (1930–1945), marcado por autoritarismo, centralização do poder, e criação de leis trabalhistas.",
  "guerra fria conflito ideológico e geopolítico entre estados unidos (capitalismo) e união soviética (socialismo) que dividiu o mundo de 1947 até 1991, sem confrontos diretos entre as superpotências.",
  "ditadura militar no brasil regime autoritário instaurado em 1964 com apoio das forças armadas, durando até 1985, caracterizado por censura, repressão e suspensão de direitos civis.",
  "iluminismo movimento intelectual do século xviii que defendia o uso da razão, liberdade de pensamento e fim do absolutismo, influenciando revoluções como a francesa.",
  "revolução francesa movimento revolucionário que começou em 1789, derrubou a monarquia absolutista e espalhou ideais de liberdade, igualdade e fraternidade na europa.",
  "imperialismo europeu prática de dominação política e econômica dos países europeus sobre a áfrica e ásia no século xix, motivada pela busca de matérias-primas e mercados consumidores.",
  "segunda guerra mundial conflito global de 1939 a 1945 causado pela expansão nazista e insatisfação do tratado de versalhes, terminou com a derrota da alemanha, japão e itália.",
  "abolição da escravidão no brasil processo que culminou com a lei áurea de 1888, abolindo oficialmente a escravidão após pressões internas e externas, mas sem integração social dos ex-escravizados.",
  "proclamação da república brasileira aconteceu em 1889, com o fim da monarquia e o início do regime republicano no brasil, liderado por militares e influenciado por ideias positivistas.",
  "independência do brasil processo político de ruptura com portugal em 1822, liderado por dom pedro i, marcando o início da soberania nacional.",
  "nova república fase iniciada após o fim da ditadura militar em 1985, com redemocratização do brasil e elaboração da constituição de 1988.",
  "movimento operário brasileiro organização dos trabalhadores por melhores condições e direitos trabalhistas, crescendo no século xx, com destaque para greves e sindicatos.",
  "primeira guerra mundial conflito global entre 1914 e 1918 causado por disputas imperialistas, alianças militares e o assassinato do arquiduque francisco ferdinando.",
  "revolução industrial transformação econômica e social iniciada no século xviii, com a invenção da máquina a vapor e o desenvolvimento de fábricas, mudando a produção e o trabalho.",
  "descobrimento do brasil chegada dos portugueses em 1500, liderados por pedro álvares cabral, marcando o início da exploração e colonização do território brasileiro.",
  "inconfidência baiana revolta social ocorrida em 1798 na bahia, com forte caráter popular, defendendo a abolição da escravidão e a proclamação da república.",
  "guerra do paraguai maior conflito armado da américa do sul (1864-1870), onde o brasil, argentina e uruguai (tríplice aliança) lutaram contra o paraguai, resultando em grande devastação para o último.",
  "crise de 1929 colapso da bolsa de valores de nova york que gerou uma grande depressão econômica global, impactando a produção, o emprego e o comércio internacional.",
  "globalização processo de intensificação das conexões econômicas, sociais, culturais e políticas em escala mundial, impulsionado pela tecnologia e pela liberalização do comércio.",
  "apartheid regime de segregação racial imposto na áfrica do sul de 1948 a 1994, que privava os direitos da maioria negra em favor da minoria branca.",
  "queda do muro de berlim evento de 1989 que simbolizou o fim da guerra fria e a reunificação da alemanha, marcando o colapso dos regimes comunistas no leste europeu.",
  "revolução russa série de eventos em 1917 que derrubaram a monarquia czarista e estabeleceram o primeiro estado socialista do mundo, liderado pelos bolcheviques de lenin.",
  "nazismo ideologia totalitária de extrema-direita liderada por hitler na alemanha (1933-1945), baseada em racismo, nacionalismo extremo e expansionismo.",
  "democracia sistema de governo onde o poder é exercido pelo povo, diretamente ou através de representantes eleitos.",
  "feudalismo sistema social, econômico e político da idade média, baseado na relação de suserania e vassalagem, com a terra como principal riqueza.",
  "capitalismo sistema econômico e social baseado na propriedade privada dos meios de produção, busca do lucro e livre mercado.",
  "socialismo teoria política e econômica que defende a propriedade coletiva ou pública dos meios de produção e a distribuição igualitária da riqueza.",
  "comunismo sistema social e econômico que visa uma sociedade sem classes, sem propriedade privada e sem estado, onde os meios de produção são de propriedade comum.",
  "reforma protestante movimento religioso do século xvi que questionou a autoridade da igreja católica, levando ao surgimento de novas denominações cristãs.",
  "contrarreforma resposta da igreja católica à reforma protestante, com medidas como o concílio de trento e a inquisição, buscando reformar-se internamente e combater o protestantismo.",
  "descobrimentos portugueses período de grandes navegações e explorações marítimas por portugal nos séculos xv e xvi, expandindo o comércio e o conhecimento geográfico.",
  "renascimento comercial e urbano resurgimento do comércio e crescimento das cidades na europa medieval, impulsionando a economia e a mudança social.",
  "absolutismo monarquia forma de governo onde o rei detém poder total, sem limites, concentrando em suas mãos os poderes legislativo, executivo e judiciário."
];