export const palavrasjs = [
  "let declara uma variável que pode mudar de valor",
  "const declara uma variável que não pode mudar de valor",
  "var declara uma variável forma antiga evite usar",
  "number representa números inteiros ou decimais",
  "string representa texto",
  "boolean representa verdadeiro ou falso",
  "undefined valor de uma variável que não tem valor atribuído",
  "null valor que representa a ausência intencional de um valor",
  "symbol valor único usado para identificar propriedades de objetos",
  "object coleção de informações organizadas por nome e valor",
  "array lista de itens ordenados",
  "+ adição",
  "- subtração",
  "* multiplicação",
  "/ divisão",
  "% resto de uma divisão",
  "** potência",
  "++ aumenta o valor de uma variável em 1",
  "-- diminui o valor de uma variável em 1",
  "+= adiciona um valor a uma variável",
  "== igual a compara os valores",
  "=== estritamente igual a compara valor e tipo",
  "!= diferente de compara os valores",
  "!== estritamente diferente de compara valor e tipo",
  "> maior que",
  "< menor que",
  ">= maior ou igual a",
  "<= menor ou igual a",
  "&& e lógico verdadeiro se ambos forem verdadeiros",
  "|| ou lógico verdadeiro se um ou outro for verdadeiro",
  "! não lógico inverte o valor",
  "if se uma condição for verdadeira faça algo",
  "else if senão se outra condição for verdadeira faça outra coisa",
  "else senão faça outra coisa",
  "switch escolhe um bloco de código para executar baseado em um valor",
  "case um dos valores a serem comparados no switch",
  "break sai do switch ou do loop",
  "default o que fazer se nenhum case corresponder no switch",
  "for repete um bloco de código um número específico de vezes",
  "while repete um bloco de código enquanto uma condição for verdadeira",
  "do...while repete um bloco de código pelo menos uma vez e depois verifica a condição",
  "for...in passa por todas as propriedades de um objeto",
  "for...of passa por todos os valores de algo que pode ser iterado como um array",
  "function declara uma função um bloco de código reutilizável",
  "return devolve um valor de uma função",
  "=> forma curta de escrever uma função",
  "arguments lista de todos os valores passados para uma função",
  "{} cria um objeto literal",
  ". acessa uma propriedade de um objeto",
  "[] acessa um item de um array ou propriedade de um objeto",
  "new cria um novo objeto a partir de uma classe",
  "this refere se ao objeto atual",
  "class declara um modelo para criar objetos",
  "constructor método especial para criar e configurar um objeto de uma classe",
  "extends permite que uma classe herde propriedades e métodos de outra",
  "super chama o construtor ou métodos da classe pai",
  "push adiciona um item ao final de um array",
  "pop remove o último item de um array",
  "unshift adiciona um item ao início de um array",
  "shift remove o primeiro item de um array",
  "splice adiciona ou remove itens de um array em qualquer posição",
  "slice cria uma cópia de parte de um array",
  "foreach executa uma função para cada item de um array",
  "map cria um novo array com os resultados de uma função aplicada a cada item",
  "filter cria um novo array com os itens que passam em um teste",
  "reduce reduz um array a um único valor executando uma função em cada item",
  "find retorna o primeiro item de um array que corresponde a uma condição",
  "some verifica se pelo menos um item de um array corresponde a uma condição",
  "every verifica se todos os itens de um array correspondem a uma condição",
  "sort organiza os itens de um array",
  "length retorna o número de caracteres em um texto ou itens em um array",
  "touppercase converte um texto para letras maiúsculas",
  "tolowercase converte um texto para letras minúsculas",
  "indexof encontra a primeira posição de um texto dentro de outro",
  "lastindexof encontra a última posição de um texto dentro de outro",
  "slice extrai uma parte de um texto",
  "replace substitui uma parte de um texto por outro",
  "split divide um texto em um array de substrings",
  "trim remove espaços em branco do início e do fim de um texto",
  "startswith verifica se um texto começa com outro texto",
  "endswith verifica se um texto termina com outro texto",
  "includes verifica se um texto contém outro texto",
  "trimstart remove espaços do início de um texto",
  "trimend remove espaços do final de um texto",
  "padstart adiciona caracteres ao início de um texto até atingir um tamanho",
  "padend adiciona caracteres ao final de um texto até atingir um tamanho",
  "document representa a página html",
  "getelementbyid pega um elemento html pelo seu id",
  "getelementsbyclassname pega vários elementos html pela sua classe",
  "getelementsbytagname pega vários elementos html pela sua tag",
  "queryselector pega o primeiro elemento que corresponde a um seletor css",
  "queryselectorall pega todos os elementos que correspondem a um seletor css",
  "textcontent pega ou muda o texto de um elemento",
  "innerhtml pega ou muda o html dentro de um elemento",
  "setattribute define um valor para um atributo de um elemento",
  "getattribute pega o valor de um atributo de um elemento",
  "classlist a lista de classes de um elemento",
  "add adiciona uma classe a um elemento",
  "remove remove uma classe de um elemento",
  "toggle adiciona ou remove uma classe de um elemento",
  "style acessa o estilo css de um elemento",
  "createelement cria um novo elemento html",
  "appendchild adiciona um elemento dentro de outro no final",
  "removechild remove um elemento de dentro de outro",
  "insertbefore adiciona um elemento dentro de outro antes de outro elemento",
  "remove remove o elemento do seu pai",
  "addeventlistener espera por um evento acontecer em um elemento",
  "click acontece quando um elemento é clicado",
  "mouseover acontece quando o mouse passa por cima de um elemento",
  "mouseout acontece quando o mouse sai de um elemento",
  "keydown acontece quando uma tecla é pressionada",
  "keyup acontece quando uma tecla é solta",
  "submit acontece quando um formulário é enviado",
  "change acontece quando o valor de um campo de formulário muda",
  "load acontece quando uma página ou imagem termina de carregar",
  "scroll acontece quando a barra de rolagem é movida",
  "resize acontece quando a janela do navegador muda de tamanho",
  "touchstart acontece quando um dedo toca a tela",
  "touchmove acontece quando um dedo se move na tela",
  "touchend acontece quando um dedo é removido da tela",
  "touchcancel acontece quando um toque é interrompido",
  "window representa a janela do navegador",
  "event informações sobre o evento que aconteceu",
  "prompt mostra uma caixa de diálogo que pede uma entrada de texto",
  "alert mostra uma caixa de alerta com uma mensagem",
  "confirm mostra uma caixa de diálogo com uma pergunta e botões ok/cancelar",
  "parseint converte uma string para um número inteiro",
  "parsefloat converte uma string para um número decimal",
  "isnan verifica se um valor é 'not a number'",
  "isfinite verifica se um valor é um número finito",
  "tostring converte um valor para string",
  "valueof retorna o valor primitivo de um objeto",
  "date representa datas e horas",
  "math objeto que fornece funções e constantes matemáticas",
  "json objeto para trabalhar com dados json (parse e stringify)",
  "localstorage armazena dados no navegador sem data de expiração",
  "sessionstorage armazena dados no navegador para a sessão atual",
  "cookie armazena pequenos pedaços de dados no navegador com data de expiração",
  "settimeout executa uma função depois de um certo tempo",
  "setinterval executa uma função repetidamente com um intervalo de tempo",
  "cleartimeout cancela um timeout agendado",
  "clearinterval cancela um interval agendado",
  "try...catch lida com erros em um bloco de código",
  "throw lança uma exceção (erro) personalizada",
  "async/await para trabalhar com operações assíncronas de forma mais fácil",
  "promise representa o resultado eventual (sucesso ou falha) de uma operação assíncrona",
  "fetch faz requisições de rede para obter recursos (ex: apis)",
  "console.log exibe mensagens no console do navegador ou ambiente node.js",
  "console.error exibe mensagens de erro no console",
  "console.warn exibe mensagens de aviso no console",
  "console.info exibe mensagens informativas no console",
  "console.table exibe dados tabulares no console",
  "type of verifica o tipo de um valor",
  "instanceof verifica se um objeto é uma instância de uma classe específica",
  "delete remove uma propriedade de um objeto ou um elemento de um array"
];
