export const palavraspy = [
  "def declara uma função",
  "return retorna um valor da função",
  "if executa um bloco de código se a condição for verdadeira",
  "elif verifica outra condição se a anterior for falsa",
  "else executa um bloco se todas as condições anteriores forem falsas",
  "for cria um loop repetindo algo várias vezes",
  "while loop que repete enquanto uma condição for verdadeira",
  "break sai do loop imediatamente",
  "continue pula para a próxima repetição do loop",
  "pass não faz nada usado como espaço vazio",
  "import permite usar códigos de outros arquivos",
  "from permite importar partes específicas de outros arquivos",
  "as dá um novo nome para algo importado",
  "class cria um tipo de objeto",
  "self refere se ao próprio objeto dentro de uma classe",
  "__init__ método especial para criar um objeto de uma classe",
  "try inicia um bloco para lidar com erros",
  "except bloco que diz o que fazer se um erro específico acontecer",
  "finally bloco que sempre executa mesmo se houver erro ou não",
  "with usado para gerenciar recursos como arquivos de forma segura",
  "lambda cria uma função pequena e rápida sem nome",
  "print mostra algo na tela",
  "input pede informação para o usuário",
  "int converte algo para um número inteiro",
  "float converte algo para um número decimal",
  "str converte algo para texto",
  "list cria uma lista que pode ser alterada",
  "tuple cria uma lista que não pode ser alterada",
  "dict cria um dicionário com pares de chave e valor",
  "set coleção de itens únicos sem ordem específica",
  "len retorna o número de itens em algo",
  "range cria uma sequência de números",
  "open abre um arquivo",
  "read lê o conteúdo de um arquivo",
  "write escreve conteúdo em um arquivo",
  "append adiciona um item ao final de uma lista",
  "pop remove e devolve um item de uma lista",
  "sort organiza os itens de uma lista",
  "reverse inverte a ordem dos itens de uma lista",
  "upper converte um texto para letras maiúsculas",
  "lower converte um texto para letras minúsculas",
  "strip remove espaços em branco do início e do fim de um texto",
  "split divide um texto em uma lista de partes",
  "join junta os itens de uma lista em um texto",
  "int() converte para inteiro",
  "float() converte para decimal",
  "str() converte para texto",
  "is compara se duas coisas são o mesmo objeto",
  "== compara se duas coisas têm o mesmo valor",
  "!= diferente de",
  "< menor que",
  "> maior que",
  "<= menor ou igual a",
  ">= maior ou igual a",
  "and verdadeiro se ambas as condições forem verdadeiras",
  "or verdadeiro se pelo menos uma condição for verdadeira",
  "not inverte o valor de uma condição",
  "true valor booleano verdadeiro",
  "false valor booleano falso",
  "none representa a ausência de um valor",
  "__name__ nome do arquivo atual",
  "if __name__ == '__main__' ponto de início do programa",
  "def func(*args **kwargs) recebe vários argumentos de diferentes formas",
  "del remove um objeto ou item",
  "global declara uma variável global",
  "nonlocal declara uma variável não local em uma função aninhada",
  "assert verifica se uma condição é verdadeira; se não for, levanta um erro",
  "yield usado em funções geradoras para produzir uma sequência de resultados",
  "async usado para definir uma função assíncrona (coroutine)",
  "await usado para aguardar a conclusão de uma operação assíncrona",
  "raise levanta uma exceção (erro)",
  "finally bloco que sempre executa, tenha ocorrido um erro ou não",
  "type() retorna o tipo de um objeto",
  "dir() retorna uma lista de nomes de atributos de um objeto",
  "help() invoca o sistema de ajuda embutido",
  "isinstance() verifica se um objeto é uma instância de uma classe específica",
  "issubclass() verifica se uma classe é uma subclasse de outra",
  "callable() verifica se um objeto pode ser chamado (é uma função ou método)",
  "exec() executa código python dinamicamente",
  "eval() avalia uma expressão python",
  "bytearray() retorna um novo array de bytes mutável",
  "bytes() retorna um novo objeto de bytes imutável",
  "memoryview() retorna um objeto de \"memory view\" para uma matriz de bytes",
  "frozenset() retorna um novo objeto \"frozenset\" imutável",
  "complex() retorna um número complexo",
  "divmod() retorna o quociente e o resto da divisão",
  "enumerate() adiciona um contador a um iterável",
  "filter() constrói um iterador a partir de elementos de um iterável para os quais uma função retorna verdadeiro",
  "map() aplica uma função a todos os itens em um iterável",
  "max() retorna o maior item em um iterável ou o maior de dois ou mais argumentos",
  "min() retorna o menor item em um iterável ou o menor de dois ou mais argumentos",
  "next() retorna o próximo item de um iterador",
  "pow() retorna o valor de x elevado à potência de y",
  "reversed() retorna um iterador reverso",
  "round() arredonda um número",
  "sum() soma os itens de um iterável",
  "zip() combina múltiplos iteráveis em tuplas"
];